version: "3.3"

services:
  rabbit:
    image: rabbitmq:3.9.7-management-alpine
    container_name: "rabbit"
    # environment:
    #   RABBITMQ_DEFAULT_USER: user
    #   RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    volumes:
      - ./rabbit/definitions.json:/opt/definitions.json
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    # logging:
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
    # driver: "syslog"
    # options:
    #   syslog-address: ${LOGGING_HOST}
    #   tag: rabbit

  # api:
  #   image: node:16.20.0
  #   restart: 'on-failure'
  #   container_name: baluu_api
  #   hostname: baluu_api
  #   # deploy:
  #   #   replicas: 1
  #   expose:
  #     - ${API_PORT}
  #   environment:

  #   volumes:
  #     - ${MEDIA_PATH}:/var/www/images
  #     - ${SOURCE_PATH}:/var/www/api
  #   working_dir: /var/www/api
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: ${LOGGING_HOST}
  #       tag: baluu_api
  #   command: make run
